version: "1"
rules:
  - base: master
    upstream: gregkh:master
    mergeMethod: hardreset
  - base: linux-5.3.y
    upstream: gregkh:linux-5.3.y
    mergeMethod: hardreset
  - base: linux-5.4.y
    upstream: gregkh:linux-5.4.y
    mergeMethod: hardreset
  - base: linux-5.5.y
    upstream: gregkh:linux-5.5.y
    mergeMethod: hardreset
